### ISSUE TITLE
Is it possible to enrich the agents with my own data ? 

### ISSUE THREAD

**Issue by luancaarvalho** [Itakello/standford_experiment_simulation#2]
Hello!

First, congratulations on the project, amazing paper!

I'm curious about one thing. Is it possible to pass any data to the agents besides my prompt?

Thank you

**Comment by Itakello** [comment]
Sure thing! The framework is highly customizable and you should be able to define the entire prompt for each agent. Just follow the instructions in the README. If you have any questions, just open another issue

**Comment by luancaarvalho** [comment]
@Itakello Can I customize my agents beyond just changing their prompts? For example, can they access data in my PostgreSQL or index documents to expand their knowledge base?

**Comment by Itakello** [comment]
You have to manually change the code to do that. By default you can just connect to a MongoDB instance and have there all the data.

**Comment by luancaarvalho** [comment]
So if I store all my document data in a MongoDB index, will it automatically become part of my agent's knowledge base, or do I need to change anything else in the code?

**Comment by Itakello** [comment]
No, the mongoDB is used to store the conversation configuration, the prompts and the interactions between the agents. And is automatically handled by the framework.
